// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/dag/testpb/order.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Approved      bool                   `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pkg_dag_testpb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dag_testpb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pkg_dag_testpb_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

var File_pkg_dag_testpb_order_proto protoreflect.FileDescriptor

const file_pkg_dag_testpb_order_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/dag/testpb/order.proto\x12\n" +
	"dag.testpb\"n\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapprovedB7Z5github.com/solo-kingdom/uniface/pkg/dag/testpb;testpbb\x06proto3"

var (
	file_pkg_dag_testpb_order_proto_rawDescOnce sync.Once
	file_pkg_dag_testpb_order_proto_rawDescData []byte
)

func file_pkg_dag_testpb_order_proto_rawDescGZIP() []byte {
	file_pkg_dag_testpb_order_proto_rawDescOnce.Do(func() {
		file_pkg_dag_testpb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_dag_testpb_order_proto_rawDesc), len(file_pkg_dag_testpb_order_proto_rawDesc)))
	})
	return file_pkg_dag_testpb_order_proto_rawDescData
}

var file_pkg_dag_testpb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_dag_testpb_order_proto_goTypes = []any{
	(*Order)(nil), // 0: dag.testpb.Order
}
var file_pkg_dag_testpb_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_dag_testpb_order_proto_init() }
func file_pkg_dag_testpb_order_proto_init() {
	if File_pkg_dag_testpb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_dag_testpb_order_proto_rawDesc), len(file_pkg_dag_testpb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_dag_testpb_order_proto_goTypes,
		DependencyIndexes: file_pkg_dag_testpb_order_proto_depIdxs,
		MessageInfos:      file_pkg_dag_testpb_order_proto_msgTypes,
	}.Build()
	File_pkg_dag_testpb_order_proto = out.File
	file_pkg_dag_testpb_order_proto_goTypes = nil
	file_pkg_dag_testpb_order_proto_depIdxs = nil
}
