// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceStatus 实例运行状态。
type InstanceStatus int32

const (
	InstanceStatus_INSTANCE_STATUS_UNSPECIFIED  InstanceStatus = 0
	InstanceStatus_INSTANCE_STATUS_RUNNING      InstanceStatus = 1
	InstanceStatus_INSTANCE_STATUS_WAITING      InstanceStatus = 2
	InstanceStatus_INSTANCE_STATUS_COMPENSATING InstanceStatus = 3
	InstanceStatus_INSTANCE_STATUS_COMPLETED    InstanceStatus = 4
	InstanceStatus_INSTANCE_STATUS_FAILED       InstanceStatus = 5
	InstanceStatus_INSTANCE_STATUS_COMPENSATED  InstanceStatus = 6
	InstanceStatus_INSTANCE_STATUS_CANCELLED    InstanceStatus = 7
)

// Enum value maps for InstanceStatus.
var (
	InstanceStatus_name = map[int32]string{
		0: "INSTANCE_STATUS_UNSPECIFIED",
		1: "INSTANCE_STATUS_RUNNING",
		2: "INSTANCE_STATUS_WAITING",
		3: "INSTANCE_STATUS_COMPENSATING",
		4: "INSTANCE_STATUS_COMPLETED",
		5: "INSTANCE_STATUS_FAILED",
		6: "INSTANCE_STATUS_COMPENSATED",
		7: "INSTANCE_STATUS_CANCELLED",
	}
	InstanceStatus_value = map[string]int32{
		"INSTANCE_STATUS_UNSPECIFIED":  0,
		"INSTANCE_STATUS_RUNNING":      1,
		"INSTANCE_STATUS_WAITING":      2,
		"INSTANCE_STATUS_COMPENSATING": 3,
		"INSTANCE_STATUS_COMPLETED":    4,
		"INSTANCE_STATUS_FAILED":       5,
		"INSTANCE_STATUS_COMPENSATED":  6,
		"INSTANCE_STATUS_CANCELLED":    7,
	}
)

func (x InstanceStatus) Enum() *InstanceStatus {
	p := new(InstanceStatus)
	*p = x
	return p
}

func (x InstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (InstanceStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x InstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceStatus.Descriptor instead.
func (InstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// GraphPinPolicy 图版本绑定策略。
type GraphPinPolicy int32

const (
	GraphPinPolicy_GRAPH_PIN_POLICY_UNSPECIFIED GraphPinPolicy = 0
	GraphPinPolicy_GRAPH_PIN_ON_START           GraphPinPolicy = 1
	GraphPinPolicy_GRAPH_PIN_ON_NODE            GraphPinPolicy = 2
	GraphPinPolicy_GRAPH_PIN_EXPLICIT           GraphPinPolicy = 3
)

// Enum value maps for GraphPinPolicy.
var (
	GraphPinPolicy_name = map[int32]string{
		0: "GRAPH_PIN_POLICY_UNSPECIFIED",
		1: "GRAPH_PIN_ON_START",
		2: "GRAPH_PIN_ON_NODE",
		3: "GRAPH_PIN_EXPLICIT",
	}
	GraphPinPolicy_value = map[string]int32{
		"GRAPH_PIN_POLICY_UNSPECIFIED": 0,
		"GRAPH_PIN_ON_START":           1,
		"GRAPH_PIN_ON_NODE":            2,
		"GRAPH_PIN_EXPLICIT":           3,
	}
)

func (x GraphPinPolicy) Enum() *GraphPinPolicy {
	p := new(GraphPinPolicy)
	*p = x
	return p
}

func (x GraphPinPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphPinPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (GraphPinPolicy) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x GraphPinPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphPinPolicy.Descriptor instead.
func (GraphPinPolicy) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// TerminalOutcome 终止节点结果。
type TerminalOutcome int32

const (
	TerminalOutcome_TERMINAL_OUTCOME_UNSPECIFIED TerminalOutcome = 0
	TerminalOutcome_TERMINAL_OUTCOME_SUCCESS     TerminalOutcome = 1
	TerminalOutcome_TERMINAL_OUTCOME_FAILURE     TerminalOutcome = 2
)

// Enum value maps for TerminalOutcome.
var (
	TerminalOutcome_name = map[int32]string{
		0: "TERMINAL_OUTCOME_UNSPECIFIED",
		1: "TERMINAL_OUTCOME_SUCCESS",
		2: "TERMINAL_OUTCOME_FAILURE",
	}
	TerminalOutcome_value = map[string]int32{
		"TERMINAL_OUTCOME_UNSPECIFIED": 0,
		"TERMINAL_OUTCOME_SUCCESS":     1,
		"TERMINAL_OUTCOME_FAILURE":     2,
	}
)

func (x TerminalOutcome) Enum() *TerminalOutcome {
	p := new(TerminalOutcome)
	*p = x
	return p
}

func (x TerminalOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (TerminalOutcome) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x TerminalOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalOutcome.Descriptor instead.
func (TerminalOutcome) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// EntityRef 标识一条实体实例线。
type EntityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRef) Reset() {
	*x = EntityRef{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRef) ProtoMessage() {}

func (x *EntityRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRef.ProtoReflect.Descriptor instead.
func (*EntityRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *EntityRef) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

// EntityTypeKey 实体类型二元组。
type EntityTypeKey struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EntityType           string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	PayloadSchemaVersion string                 `protobuf:"bytes,2,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EntityTypeKey) Reset() {
	*x = EntityTypeKey{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityTypeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityTypeKey) ProtoMessage() {}

func (x *EntityTypeKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityTypeKey.ProtoReflect.Descriptor instead.
func (*EntityTypeKey) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *EntityTypeKey) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityTypeKey) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

// GraphVersion 图版本标识。
type GraphVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraphId       string                 `protobuf:"bytes,1,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphVersion) Reset() {
	*x = GraphVersion{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphVersion) ProtoMessage() {}

func (x *GraphVersion) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphVersion.ProtoReflect.Descriptor instead.
func (*GraphVersion) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *GraphVersion) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *GraphVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RetryPolicy 重试策略。
type RetryPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts    int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	InitialBackoff *durationpb.Duration   `protobuf:"bytes,2,opt,name=initial_backoff,json=initialBackoff,proto3" json:"initial_backoff,omitempty"`
	MaxBackoff     *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_backoff,json=maxBackoff,proto3" json:"max_backoff,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoff() *durationpb.Duration {
	if x != nil {
		return x.InitialBackoff
	}
	return nil
}

func (x *RetryPolicy) GetMaxBackoff() *durationpb.Duration {
	if x != nil {
		return x.MaxBackoff
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06dag.v1\x1a\x1egoogle/protobuf/duration.proto\"(\n" +
	"\tEntityRef\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"f\n" +
	"\rEntityTypeKey\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x124\n" +
	"\x16payload_schema_version\x18\x02 \x01(\tR\x14payloadSchemaVersion\"C\n" +
	"\fGraphVersion\x12\x19\n" +
	"\bgraph_id\x18\x01 \x01(\tR\agraphId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xb0\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12B\n" +
	"\x0finitial_backoff\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0einitialBackoff\x12:\n" +
	"\vmax_backoff\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"maxBackoff*\x88\x02\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17INSTANCE_STATUS_RUNNING\x10\x01\x12\x1b\n" +
	"\x17INSTANCE_STATUS_WAITING\x10\x02\x12 \n" +
	"\x1cINSTANCE_STATUS_COMPENSATING\x10\x03\x12\x1d\n" +
	"\x19INSTANCE_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16INSTANCE_STATUS_FAILED\x10\x05\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_COMPENSATED\x10\x06\x12\x1d\n" +
	"\x19INSTANCE_STATUS_CANCELLED\x10\a*y\n" +
	"\x0eGraphPinPolicy\x12 \n" +
	"\x1cGRAPH_PIN_POLICY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12GRAPH_PIN_ON_START\x10\x01\x12\x15\n" +
	"\x11GRAPH_PIN_ON_NODE\x10\x02\x12\x16\n" +
	"\x12GRAPH_PIN_EXPLICIT\x10\x03*o\n" +
	"\x0fTerminalOutcome\x12 \n" +
	"\x1cTERMINAL_OUTCOME_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TERMINAL_OUTCOME_SUCCESS\x10\x01\x12\x1c\n" +
	"\x18TERMINAL_OUTCOME_FAILURE\x10\x02B2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(InstanceStatus)(0),         // 0: dag.v1.InstanceStatus
	(GraphPinPolicy)(0),         // 1: dag.v1.GraphPinPolicy
	(TerminalOutcome)(0),        // 2: dag.v1.TerminalOutcome
	(*EntityRef)(nil),           // 3: dag.v1.EntityRef
	(*EntityTypeKey)(nil),       // 4: dag.v1.EntityTypeKey
	(*GraphVersion)(nil),        // 5: dag.v1.GraphVersion
	(*RetryPolicy)(nil),         // 6: dag.v1.RetryPolicy
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_common_proto_depIdxs = []int32{
	7, // 0: dag.v1.RetryPolicy.initial_backoff:type_name -> google.protobuf.Duration
	7, // 1: dag.v1.RetryPolicy.max_backoff:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
