// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entity.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntitySnapshot 实体快照。
type EntitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *EntityRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	TypeKey       *EntityTypeKey         `protobuf:"bytes,2,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntitySnapshot) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *EntitySnapshot) GetTypeKey() *EntityTypeKey {
	if x != nil {
		return x.TypeKey
	}
	return nil
}

func (x *EntitySnapshot) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EntitySnapshot) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EntityInstance 实体实例元数据。
type EntityInstance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            *EntityRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	TypeKey        *EntityTypeKey         `protobuf:"bytes,2,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	Status         InstanceStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=dag.v1.InstanceStatus" json:"status,omitempty"`
	Sequence       int64                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CurrentNodeId  string                 `protobuf:"bytes,5,opt,name=current_node_id,json=currentNodeId,proto3" json:"current_node_id,omitempty"`
	GraphVersion   *GraphVersion          `protobuf:"bytes,6,opt,name=graph_version,json=graphVersion,proto3" json:"graph_version,omitempty"`
	GraphPinPolicy GraphPinPolicy         `protobuf:"varint,7,opt,name=graph_pin_policy,json=graphPinPolicy,proto3,enum=dag.v1.GraphPinPolicy" json:"graph_pin_policy,omitempty"`
	Parent         *EntityRef             `protobuf:"bytes,8,opt,name=parent,proto3" json:"parent,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityInstance) Reset() {
	*x = EntityInstance{}
	mi := &file_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInstance) ProtoMessage() {}

func (x *EntityInstance) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInstance.ProtoReflect.Descriptor instead.
func (*EntityInstance) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

func (x *EntityInstance) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *EntityInstance) GetTypeKey() *EntityTypeKey {
	if x != nil {
		return x.TypeKey
	}
	return nil
}

func (x *EntityInstance) GetStatus() InstanceStatus {
	if x != nil {
		return x.Status
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *EntityInstance) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EntityInstance) GetCurrentNodeId() string {
	if x != nil {
		return x.CurrentNodeId
	}
	return ""
}

func (x *EntityInstance) GetGraphVersion() *GraphVersion {
	if x != nil {
		return x.GraphVersion
	}
	return nil
}

func (x *EntityInstance) GetGraphPinPolicy() GraphPinPolicy {
	if x != nil {
		return x.GraphPinPolicy
	}
	return GraphPinPolicy_GRAPH_PIN_POLICY_UNSPECIFIED
}

func (x *EntityInstance) GetParent() *EntityRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *EntityInstance) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EntityInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EntityInstance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// WaitSignal 等待外部信号。
type WaitSignal struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SignalName            string                 `protobuf:"bytes,1,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	AcceptedSignals       []string               `protobuf:"bytes,2,rep,name=accepted_signals,json=acceptedSignals,proto3" json:"accepted_signals,omitempty"`
	Deadline              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	OnTimeoutTargetNodeId string                 `protobuf:"bytes,4,opt,name=on_timeout_target_node_id,json=onTimeoutTargetNodeId,proto3" json:"on_timeout_target_node_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WaitSignal) Reset() {
	*x = WaitSignal{}
	mi := &file_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitSignal) ProtoMessage() {}

func (x *WaitSignal) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitSignal.ProtoReflect.Descriptor instead.
func (*WaitSignal) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{2}
}

func (x *WaitSignal) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *WaitSignal) GetAcceptedSignals() []string {
	if x != nil {
		return x.AcceptedSignals
	}
	return nil
}

func (x *WaitSignal) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *WaitSignal) GetOnTimeoutTargetNodeId() string {
	if x != nil {
		return x.OnTimeoutTargetNodeId
	}
	return ""
}

// SpawnSpec 子实例创建规格。
type SpawnSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            *EntityRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	TypeKey        *EntityTypeKey         `protobuf:"bytes,2,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	InitialPayload *anypb.Any             `protobuf:"bytes,3,opt,name=initial_payload,json=initialPayload,proto3" json:"initial_payload,omitempty"`
	Graph          *GraphVersion          `protobuf:"bytes,4,opt,name=graph,proto3" json:"graph,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpawnSpec) Reset() {
	*x = SpawnSpec{}
	mi := &file_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnSpec) ProtoMessage() {}

func (x *SpawnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnSpec.ProtoReflect.Descriptor instead.
func (*SpawnSpec) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnSpec) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *SpawnSpec) GetTypeKey() *EntityTypeKey {
	if x != nil {
		return x.TypeKey
	}
	return nil
}

func (x *SpawnSpec) GetInitialPayload() *anypb.Any {
	if x != nil {
		return x.InitialPayload
	}
	return nil
}

func (x *SpawnSpec) GetGraph() *GraphVersion {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *SpawnSpec) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// EntityMutation 计算单元返回的变更意图。
type EntityMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Intent:
	//
	//	*EntityMutation_Update
	//	*EntityMutation_Spawn
	//	*EntityMutation_Wait
	//	*EntityMutation_Complete
	//	*EntityMutation_Fail
	Intent        isEntityMutation_Intent `protobuf_oneof:"intent"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMutation) Reset() {
	*x = EntityMutation{}
	mi := &file_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMutation) ProtoMessage() {}

func (x *EntityMutation) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMutation.ProtoReflect.Descriptor instead.
func (*EntityMutation) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{4}
}

func (x *EntityMutation) GetIntent() isEntityMutation_Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *EntityMutation) GetUpdate() *EntitySnapshot {
	if x != nil {
		if x, ok := x.Intent.(*EntityMutation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *EntityMutation) GetSpawn() *SpawnList {
	if x != nil {
		if x, ok := x.Intent.(*EntityMutation_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *EntityMutation) GetWait() *WaitSignal {
	if x != nil {
		if x, ok := x.Intent.(*EntityMutation_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *EntityMutation) GetComplete() TerminalOutcome {
	if x != nil {
		if x, ok := x.Intent.(*EntityMutation_Complete); ok {
			return x.Complete
		}
	}
	return TerminalOutcome_TERMINAL_OUTCOME_UNSPECIFIED
}

func (x *EntityMutation) GetFail() *FailIntent {
	if x != nil {
		if x, ok := x.Intent.(*EntityMutation_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

type isEntityMutation_Intent interface {
	isEntityMutation_Intent()
}

type EntityMutation_Update struct {
	Update *EntitySnapshot `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type EntityMutation_Spawn struct {
	Spawn *SpawnList `protobuf:"bytes,2,opt,name=spawn,proto3,oneof"`
}

type EntityMutation_Wait struct {
	Wait *WaitSignal `protobuf:"bytes,3,opt,name=wait,proto3,oneof"`
}

type EntityMutation_Complete struct {
	Complete TerminalOutcome `protobuf:"varint,4,opt,name=complete,proto3,enum=dag.v1.TerminalOutcome,oneof"`
}

type EntityMutation_Fail struct {
	Fail *FailIntent `protobuf:"bytes,5,opt,name=fail,proto3,oneof"`
}

func (*EntityMutation_Update) isEntityMutation_Intent() {}

func (*EntityMutation_Spawn) isEntityMutation_Intent() {}

func (*EntityMutation_Wait) isEntityMutation_Intent() {}

func (*EntityMutation_Complete) isEntityMutation_Intent() {}

func (*EntityMutation_Fail) isEntityMutation_Intent() {}

type SpawnList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*SpawnSpec           `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnList) Reset() {
	*x = SpawnList{}
	mi := &file_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnList) ProtoMessage() {}

func (x *SpawnList) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnList.ProtoReflect.Descriptor instead.
func (*SpawnList) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{5}
}

func (x *SpawnList) GetSpecs() []*SpawnSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type FailIntent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Reason              string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	TriggerCompensation bool                   `protobuf:"varint,2,opt,name=trigger_compensation,json=triggerCompensation,proto3" json:"trigger_compensation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FailIntent) Reset() {
	*x = FailIntent{}
	mi := &file_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailIntent) ProtoMessage() {}

func (x *FailIntent) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailIntent.ProtoReflect.Descriptor instead.
func (*FailIntent) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{6}
}

func (x *FailIntent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FailIntent) GetTriggerCompensation() bool {
	if x != nil {
		return x.TriggerCompensation
	}
	return false
}

var File_entity_proto protoreflect.FileDescriptor

const file_entity_proto_rawDesc = "" +
	"\n" +
	"\fentity.proto\x12\x06dag.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xb3\x01\n" +
	"\x0eEntitySnapshot\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.dag.v1.EntityRefR\x03ref\x120\n" +
	"\btype_key\x18\x02 \x01(\v2\x15.dag.v1.EntityTypeKeyR\atypeKey\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\xa0\x04\n" +
	"\x0eEntityInstance\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.dag.v1.EntityRefR\x03ref\x120\n" +
	"\btype_key\x18\x02 \x01(\v2\x15.dag.v1.EntityTypeKeyR\atypeKey\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.dag.v1.InstanceStatusR\x06status\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12&\n" +
	"\x0fcurrent_node_id\x18\x05 \x01(\tR\rcurrentNodeId\x129\n" +
	"\rgraph_version\x18\x06 \x01(\v2\x14.dag.v1.GraphVersionR\fgraphVersion\x12@\n" +
	"\x10graph_pin_policy\x18\a \x01(\x0e2\x16.dag.v1.GraphPinPolicyR\x0egraphPinPolicy\x12)\n" +
	"\x06parent\x18\b \x01(\v2\x11.dag.v1.EntityRefR\x06parent\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xca\x01\n" +
	"\n" +
	"WaitSignal\x12\x1f\n" +
	"\vsignal_name\x18\x01 \x01(\tR\n" +
	"signalName\x12)\n" +
	"\x10accepted_signals\x18\x02 \x03(\tR\x0facceptedSignals\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x128\n" +
	"\x19on_timeout_target_node_id\x18\x04 \x01(\tR\x15onTimeoutTargetNodeId\"\xf4\x01\n" +
	"\tSpawnSpec\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.dag.v1.EntityRefR\x03ref\x120\n" +
	"\btype_key\x18\x02 \x01(\v2\x15.dag.v1.EntityTypeKeyR\atypeKey\x12=\n" +
	"\x0finitial_payload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x0einitialPayload\x12*\n" +
	"\x05graph\x18\x04 \x01(\v2\x14.dag.v1.GraphVersionR\x05graph\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x82\x02\n" +
	"\x0eEntityMutation\x120\n" +
	"\x06update\x18\x01 \x01(\v2\x16.dag.v1.EntitySnapshotH\x00R\x06update\x12)\n" +
	"\x05spawn\x18\x02 \x01(\v2\x11.dag.v1.SpawnListH\x00R\x05spawn\x12(\n" +
	"\x04wait\x18\x03 \x01(\v2\x12.dag.v1.WaitSignalH\x00R\x04wait\x125\n" +
	"\bcomplete\x18\x04 \x01(\x0e2\x17.dag.v1.TerminalOutcomeH\x00R\bcomplete\x12(\n" +
	"\x04fail\x18\x05 \x01(\v2\x12.dag.v1.FailIntentH\x00R\x04failB\b\n" +
	"\x06intent\"4\n" +
	"\tSpawnList\x12'\n" +
	"\x05specs\x18\x01 \x03(\v2\x11.dag.v1.SpawnSpecR\x05specs\"W\n" +
	"\n" +
	"FailIntent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x121\n" +
	"\x14trigger_compensation\x18\x02 \x01(\bR\x13triggerCompensationB2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_entity_proto_rawDescOnce sync.Once
	file_entity_proto_rawDescData []byte
)

func file_entity_proto_rawDescGZIP() []byte {
	file_entity_proto_rawDescOnce.Do(func() {
		file_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)))
	})
	return file_entity_proto_rawDescData
}

var file_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_entity_proto_goTypes = []any{
	(*EntitySnapshot)(nil),        // 0: dag.v1.EntitySnapshot
	(*EntityInstance)(nil),        // 1: dag.v1.EntityInstance
	(*WaitSignal)(nil),            // 2: dag.v1.WaitSignal
	(*SpawnSpec)(nil),             // 3: dag.v1.SpawnSpec
	(*EntityMutation)(nil),        // 4: dag.v1.EntityMutation
	(*SpawnList)(nil),             // 5: dag.v1.SpawnList
	(*FailIntent)(nil),            // 6: dag.v1.FailIntent
	(*EntityRef)(nil),             // 7: dag.v1.EntityRef
	(*EntityTypeKey)(nil),         // 8: dag.v1.EntityTypeKey
	(*anypb.Any)(nil),             // 9: google.protobuf.Any
	(InstanceStatus)(0),           // 10: dag.v1.InstanceStatus
	(*GraphVersion)(nil),          // 11: dag.v1.GraphVersion
	(GraphPinPolicy)(0),           // 12: dag.v1.GraphPinPolicy
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(TerminalOutcome)(0),          // 14: dag.v1.TerminalOutcome
}
var file_entity_proto_depIdxs = []int32{
	7,  // 0: dag.v1.EntitySnapshot.ref:type_name -> dag.v1.EntityRef
	8,  // 1: dag.v1.EntitySnapshot.type_key:type_name -> dag.v1.EntityTypeKey
	9,  // 2: dag.v1.EntitySnapshot.payload:type_name -> google.protobuf.Any
	7,  // 3: dag.v1.EntityInstance.ref:type_name -> dag.v1.EntityRef
	8,  // 4: dag.v1.EntityInstance.type_key:type_name -> dag.v1.EntityTypeKey
	10, // 5: dag.v1.EntityInstance.status:type_name -> dag.v1.InstanceStatus
	11, // 6: dag.v1.EntityInstance.graph_version:type_name -> dag.v1.GraphVersion
	12, // 7: dag.v1.EntityInstance.graph_pin_policy:type_name -> dag.v1.GraphPinPolicy
	7,  // 8: dag.v1.EntityInstance.parent:type_name -> dag.v1.EntityRef
	13, // 9: dag.v1.EntityInstance.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: dag.v1.EntityInstance.updated_at:type_name -> google.protobuf.Timestamp
	13, // 11: dag.v1.WaitSignal.deadline:type_name -> google.protobuf.Timestamp
	7,  // 12: dag.v1.SpawnSpec.ref:type_name -> dag.v1.EntityRef
	8,  // 13: dag.v1.SpawnSpec.type_key:type_name -> dag.v1.EntityTypeKey
	9,  // 14: dag.v1.SpawnSpec.initial_payload:type_name -> google.protobuf.Any
	11, // 15: dag.v1.SpawnSpec.graph:type_name -> dag.v1.GraphVersion
	0,  // 16: dag.v1.EntityMutation.update:type_name -> dag.v1.EntitySnapshot
	5,  // 17: dag.v1.EntityMutation.spawn:type_name -> dag.v1.SpawnList
	2,  // 18: dag.v1.EntityMutation.wait:type_name -> dag.v1.WaitSignal
	14, // 19: dag.v1.EntityMutation.complete:type_name -> dag.v1.TerminalOutcome
	6,  // 20: dag.v1.EntityMutation.fail:type_name -> dag.v1.FailIntent
	3,  // 21: dag.v1.SpawnList.specs:type_name -> dag.v1.SpawnSpec
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_entity_proto_init() }
func file_entity_proto_init() {
	if File_entity_proto != nil {
		return
	}
	file_common_proto_init()
	file_entity_proto_msgTypes[4].OneofWrappers = []any{
		(*EntityMutation_Update)(nil),
		(*EntityMutation_Spawn)(nil),
		(*EntityMutation_Wait)(nil),
		(*EntityMutation_Complete)(nil),
		(*EntityMutation_Fail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_proto_rawDesc), len(file_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_proto_goTypes,
		DependencyIndexes: file_entity_proto_depIdxs,
		MessageInfos:      file_entity_proto_msgTypes,
	}.Build()
	File_entity_proto = out.File
	file_entity_proto_goTypes = nil
	file_entity_proto_depIdxs = nil
}
