// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeKind 图节点种类。
type NodeKind int32

const (
	NodeKind_NODE_KIND_UNSPECIFIED NodeKind = 0
	NodeKind_NODE_KIND_COMPUTE     NodeKind = 1
	NodeKind_NODE_KIND_WAIT        NodeKind = 2
	NodeKind_NODE_KIND_JOIN        NodeKind = 3
	NodeKind_NODE_KIND_TERMINAL    NodeKind = 4
)

// Enum value maps for NodeKind.
var (
	NodeKind_name = map[int32]string{
		0: "NODE_KIND_UNSPECIFIED",
		1: "NODE_KIND_COMPUTE",
		2: "NODE_KIND_WAIT",
		3: "NODE_KIND_JOIN",
		4: "NODE_KIND_TERMINAL",
	}
	NodeKind_value = map[string]int32{
		"NODE_KIND_UNSPECIFIED": 0,
		"NODE_KIND_COMPUTE":     1,
		"NODE_KIND_WAIT":        2,
		"NODE_KIND_JOIN":        3,
		"NODE_KIND_TERMINAL":    4,
	}
)

func (x NodeKind) Enum() *NodeKind {
	p := new(NodeKind)
	*p = x
	return p
}

func (x NodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[0].Descriptor()
}

func (NodeKind) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[0]
}

func (x NodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeKind.Descriptor instead.
func (NodeKind) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

// CompareOp 字段比较操作符。
type CompareOp int32

const (
	CompareOp_COMPARE_OP_UNSPECIFIED CompareOp = 0
	CompareOp_COMPARE_OP_EQ          CompareOp = 1
	CompareOp_COMPARE_OP_NE          CompareOp = 2
	CompareOp_COMPARE_OP_GT          CompareOp = 3
	CompareOp_COMPARE_OP_GTE         CompareOp = 4
	CompareOp_COMPARE_OP_LT          CompareOp = 5
	CompareOp_COMPARE_OP_LTE         CompareOp = 6
)

// Enum value maps for CompareOp.
var (
	CompareOp_name = map[int32]string{
		0: "COMPARE_OP_UNSPECIFIED",
		1: "COMPARE_OP_EQ",
		2: "COMPARE_OP_NE",
		3: "COMPARE_OP_GT",
		4: "COMPARE_OP_GTE",
		5: "COMPARE_OP_LT",
		6: "COMPARE_OP_LTE",
	}
	CompareOp_value = map[string]int32{
		"COMPARE_OP_UNSPECIFIED": 0,
		"COMPARE_OP_EQ":          1,
		"COMPARE_OP_NE":          2,
		"COMPARE_OP_GT":          3,
		"COMPARE_OP_GTE":         4,
		"COMPARE_OP_LT":          5,
		"COMPARE_OP_LTE":         6,
	}
)

func (x CompareOp) Enum() *CompareOp {
	p := new(CompareOp)
	*p = x
	return p
}

func (x CompareOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompareOp) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[1].Descriptor()
}

func (CompareOp) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[1]
}

func (x CompareOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompareOp.Descriptor instead.
func (CompareOp) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

// JoinPolicy Join 策略。
type JoinPolicy int32

const (
	JoinPolicy_JOIN_POLICY_UNSPECIFIED JoinPolicy = 0
	JoinPolicy_JOIN_ALL_SUCCESS        JoinPolicy = 1
	JoinPolicy_JOIN_ANY_SUCCESS        JoinPolicy = 2
)

// Enum value maps for JoinPolicy.
var (
	JoinPolicy_name = map[int32]string{
		0: "JOIN_POLICY_UNSPECIFIED",
		1: "JOIN_ALL_SUCCESS",
		2: "JOIN_ANY_SUCCESS",
	}
	JoinPolicy_value = map[string]int32{
		"JOIN_POLICY_UNSPECIFIED": 0,
		"JOIN_ALL_SUCCESS":        1,
		"JOIN_ANY_SUCCESS":        2,
	}
)

func (x JoinPolicy) Enum() *JoinPolicy {
	p := new(JoinPolicy)
	*p = x
	return p
}

func (x JoinPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_proto_enumTypes[2].Descriptor()
}

func (JoinPolicy) Type() protoreflect.EnumType {
	return &file_graph_proto_enumTypes[2]
}

func (x JoinPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinPolicy.Descriptor instead.
func (JoinPolicy) EnumDescriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

// FieldPredicate 基于 payload 字段的条件。
type FieldPredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Op            CompareOp              `protobuf:"varint,2,opt,name=op,proto3,enum=dag.v1.CompareOp" json:"op,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPredicate) Reset() {
	*x = FieldPredicate{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPredicate) ProtoMessage() {}

func (x *FieldPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPredicate.ProtoReflect.Descriptor instead.
func (*FieldPredicate) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *FieldPredicate) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldPredicate) GetOp() CompareOp {
	if x != nil {
		return x.Op
	}
	return CompareOp_COMPARE_OP_UNSPECIFIED
}

func (x *FieldPredicate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Condition 路由条件。
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Condition_Always
	//	*Condition_FieldPredicate
	Kind          isCondition_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetKind() isCondition_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Condition) GetAlways() bool {
	if x != nil {
		if x, ok := x.Kind.(*Condition_Always); ok {
			return x.Always
		}
	}
	return false
}

func (x *Condition) GetFieldPredicate() *FieldPredicate {
	if x != nil {
		if x, ok := x.Kind.(*Condition_FieldPredicate); ok {
			return x.FieldPredicate
		}
	}
	return nil
}

type isCondition_Kind interface {
	isCondition_Kind()
}

type Condition_Always struct {
	Always bool `protobuf:"varint,1,opt,name=always,proto3,oneof"`
}

type Condition_FieldPredicate struct {
	FieldPredicate *FieldPredicate `protobuf:"bytes,2,opt,name=field_predicate,json=fieldPredicate,proto3,oneof"`
}

func (*Condition_Always) isCondition_Kind() {}

func (*Condition_FieldPredicate) isCondition_Kind() {}

// Transition 出边。
type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Condition     *Condition             `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Transition) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *Transition) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Transition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// WaitNodeConfig WAIT 节点配置。
type WaitNodeConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SignalName             string                 `protobuf:"bytes,1,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	AcceptedSignals        []string               `protobuf:"bytes,2,rep,name=accepted_signals,json=acceptedSignals,proto3" json:"accepted_signals,omitempty"`
	DefaultDeadlineSeconds int64                  `protobuf:"varint,3,opt,name=default_deadline_seconds,json=defaultDeadlineSeconds,proto3" json:"default_deadline_seconds,omitempty"`
	OnTimeoutTargetNodeId  string                 `protobuf:"bytes,4,opt,name=on_timeout_target_node_id,json=onTimeoutTargetNodeId,proto3" json:"on_timeout_target_node_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WaitNodeConfig) Reset() {
	*x = WaitNodeConfig{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitNodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitNodeConfig) ProtoMessage() {}

func (x *WaitNodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitNodeConfig.ProtoReflect.Descriptor instead.
func (*WaitNodeConfig) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *WaitNodeConfig) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *WaitNodeConfig) GetAcceptedSignals() []string {
	if x != nil {
		return x.AcceptedSignals
	}
	return nil
}

func (x *WaitNodeConfig) GetDefaultDeadlineSeconds() int64 {
	if x != nil {
		return x.DefaultDeadlineSeconds
	}
	return 0
}

func (x *WaitNodeConfig) GetOnTimeoutTargetNodeId() string {
	if x != nil {
		return x.OnTimeoutTargetNodeId
	}
	return ""
}

// JoinBarrier Join 屏障。
type JoinBarrier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*JoinBarrier_ChildEntityId
	//	*JoinBarrier_CorrelationId
	Target        isJoinBarrier_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBarrier) Reset() {
	*x = JoinBarrier{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBarrier) ProtoMessage() {}

func (x *JoinBarrier) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBarrier.ProtoReflect.Descriptor instead.
func (*JoinBarrier) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

func (x *JoinBarrier) GetTarget() isJoinBarrier_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *JoinBarrier) GetChildEntityId() string {
	if x != nil {
		if x, ok := x.Target.(*JoinBarrier_ChildEntityId); ok {
			return x.ChildEntityId
		}
	}
	return ""
}

func (x *JoinBarrier) GetCorrelationId() string {
	if x != nil {
		if x, ok := x.Target.(*JoinBarrier_CorrelationId); ok {
			return x.CorrelationId
		}
	}
	return ""
}

type isJoinBarrier_Target interface {
	isJoinBarrier_Target()
}

type JoinBarrier_ChildEntityId struct {
	ChildEntityId string `protobuf:"bytes,1,opt,name=child_entity_id,json=childEntityId,proto3,oneof"`
}

type JoinBarrier_CorrelationId struct {
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3,oneof"`
}

func (*JoinBarrier_ChildEntityId) isJoinBarrier_Target() {}

func (*JoinBarrier_CorrelationId) isJoinBarrier_Target() {}

// JoinSpec JOIN 节点配置。
type JoinSpec struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Barriers                 []*JoinBarrier         `protobuf:"bytes,1,rep,name=barriers,proto3" json:"barriers,omitempty"`
	Policy                   JoinPolicy             `protobuf:"varint,2,opt,name=policy,proto3,enum=dag.v1.JoinPolicy" json:"policy,omitempty"`
	FailParentOnChildFailure bool                   `protobuf:"varint,3,opt,name=fail_parent_on_child_failure,json=failParentOnChildFailure,proto3" json:"fail_parent_on_child_failure,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JoinSpec) Reset() {
	*x = JoinSpec{}
	mi := &file_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSpec) ProtoMessage() {}

func (x *JoinSpec) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSpec.ProtoReflect.Descriptor instead.
func (*JoinSpec) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{5}
}

func (x *JoinSpec) GetBarriers() []*JoinBarrier {
	if x != nil {
		return x.Barriers
	}
	return nil
}

func (x *JoinSpec) GetPolicy() JoinPolicy {
	if x != nil {
		return x.Policy
	}
	return JoinPolicy_JOIN_POLICY_UNSPECIFIED
}

func (x *JoinSpec) GetFailParentOnChildFailure() bool {
	if x != nil {
		return x.FailParentOnChildFailure
	}
	return false
}

// NodeDef 图节点定义。
type NodeDef struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Kind              NodeKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=dag.v1.NodeKind" json:"kind,omitempty"`
	UnitId            string                 `protobuf:"bytes,3,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	CompensatorUnitId string                 `protobuf:"bytes,4,opt,name=compensator_unit_id,json=compensatorUnitId,proto3" json:"compensator_unit_id,omitempty"`
	Transitions       []*Transition          `protobuf:"bytes,5,rep,name=transitions,proto3" json:"transitions,omitempty"`
	TerminalOutcome   TerminalOutcome        `protobuf:"varint,6,opt,name=terminal_outcome,json=terminalOutcome,proto3,enum=dag.v1.TerminalOutcome" json:"terminal_outcome,omitempty"`
	WaitConfig        *WaitNodeConfig        `protobuf:"bytes,7,opt,name=wait_config,json=waitConfig,proto3" json:"wait_config,omitempty"`
	JoinSpec          *JoinSpec              `protobuf:"bytes,8,opt,name=join_spec,json=joinSpec,proto3" json:"join_spec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeDef) Reset() {
	*x = NodeDef{}
	mi := &file_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDef) ProtoMessage() {}

func (x *NodeDef) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDef.ProtoReflect.Descriptor instead.
func (*NodeDef) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{6}
}

func (x *NodeDef) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeDef) GetKind() NodeKind {
	if x != nil {
		return x.Kind
	}
	return NodeKind_NODE_KIND_UNSPECIFIED
}

func (x *NodeDef) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *NodeDef) GetCompensatorUnitId() string {
	if x != nil {
		return x.CompensatorUnitId
	}
	return ""
}

func (x *NodeDef) GetTransitions() []*Transition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

func (x *NodeDef) GetTerminalOutcome() TerminalOutcome {
	if x != nil {
		return x.TerminalOutcome
	}
	return TerminalOutcome_TERMINAL_OUTCOME_UNSPECIFIED
}

func (x *NodeDef) GetWaitConfig() *WaitNodeConfig {
	if x != nil {
		return x.WaitConfig
	}
	return nil
}

func (x *NodeDef) GetJoinSpec() *JoinSpec {
	if x != nil {
		return x.JoinSpec
	}
	return nil
}

// GraphSpec 图规格。
type GraphSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *GraphVersion          `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	EntryNodeId   string                 `protobuf:"bytes,2,opt,name=entry_node_id,json=entryNodeId,proto3" json:"entry_node_id,omitempty"`
	Nodes         map[string]*NodeDef    `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSpec) Reset() {
	*x = GraphSpec{}
	mi := &file_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSpec) ProtoMessage() {}

func (x *GraphSpec) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSpec.ProtoReflect.Descriptor instead.
func (*GraphSpec) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{7}
}

func (x *GraphSpec) GetVersion() *GraphVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GraphSpec) GetEntryNodeId() string {
	if x != nil {
		return x.EntryNodeId
	}
	return ""
}

func (x *GraphSpec) GetNodes() map[string]*NodeDef {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\x06dag.v1\x1a\fcommon.proto\"h\n" +
	"\x0eFieldPredicate\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12!\n" +
	"\x02op\x18\x02 \x01(\x0e2\x11.dag.v1.CompareOpR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"p\n" +
	"\tCondition\x12\x18\n" +
	"\x06always\x18\x01 \x01(\bH\x00R\x06always\x12A\n" +
	"\x0ffield_predicate\x18\x02 \x01(\v2\x16.dag.v1.FieldPredicateH\x00R\x0efieldPredicateB\x06\n" +
	"\x04kind\"\x7f\n" +
	"\n" +
	"Transition\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12/\n" +
	"\tcondition\x18\x02 \x01(\v2\x11.dag.v1.ConditionR\tcondition\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"\xd0\x01\n" +
	"\x0eWaitNodeConfig\x12\x1f\n" +
	"\vsignal_name\x18\x01 \x01(\tR\n" +
	"signalName\x12)\n" +
	"\x10accepted_signals\x18\x02 \x03(\tR\x0facceptedSignals\x128\n" +
	"\x18default_deadline_seconds\x18\x03 \x01(\x03R\x16defaultDeadlineSeconds\x128\n" +
	"\x19on_timeout_target_node_id\x18\x04 \x01(\tR\x15onTimeoutTargetNodeId\"j\n" +
	"\vJoinBarrier\x12(\n" +
	"\x0fchild_entity_id\x18\x01 \x01(\tH\x00R\rchildEntityId\x12'\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tH\x00R\rcorrelationIdB\b\n" +
	"\x06target\"\xa7\x01\n" +
	"\bJoinSpec\x12/\n" +
	"\bbarriers\x18\x01 \x03(\v2\x13.dag.v1.JoinBarrierR\bbarriers\x12*\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x12.dag.v1.JoinPolicyR\x06policy\x12>\n" +
	"\x1cfail_parent_on_child_failure\x18\x03 \x01(\bR\x18failParentOnChildFailure\"\xf3\x02\n" +
	"\aNodeDef\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.dag.v1.NodeKindR\x04kind\x12\x17\n" +
	"\aunit_id\x18\x03 \x01(\tR\x06unitId\x12.\n" +
	"\x13compensator_unit_id\x18\x04 \x01(\tR\x11compensatorUnitId\x124\n" +
	"\vtransitions\x18\x05 \x03(\v2\x12.dag.v1.TransitionR\vtransitions\x12B\n" +
	"\x10terminal_outcome\x18\x06 \x01(\x0e2\x17.dag.v1.TerminalOutcomeR\x0fterminalOutcome\x127\n" +
	"\vwait_config\x18\a \x01(\v2\x16.dag.v1.WaitNodeConfigR\n" +
	"waitConfig\x12-\n" +
	"\tjoin_spec\x18\b \x01(\v2\x10.dag.v1.JoinSpecR\bjoinSpec\"\xde\x01\n" +
	"\tGraphSpec\x12.\n" +
	"\aversion\x18\x01 \x01(\v2\x14.dag.v1.GraphVersionR\aversion\x12\"\n" +
	"\rentry_node_id\x18\x02 \x01(\tR\ventryNodeId\x122\n" +
	"\x05nodes\x18\x03 \x03(\v2\x1c.dag.v1.GraphSpec.NodesEntryR\x05nodes\x1aI\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.dag.v1.NodeDefR\x05value:\x028\x01*|\n" +
	"\bNodeKind\x12\x19\n" +
	"\x15NODE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NODE_KIND_COMPUTE\x10\x01\x12\x12\n" +
	"\x0eNODE_KIND_WAIT\x10\x02\x12\x12\n" +
	"\x0eNODE_KIND_JOIN\x10\x03\x12\x16\n" +
	"\x12NODE_KIND_TERMINAL\x10\x04*\x9b\x01\n" +
	"\tCompareOp\x12\x1a\n" +
	"\x16COMPARE_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCOMPARE_OP_EQ\x10\x01\x12\x11\n" +
	"\rCOMPARE_OP_NE\x10\x02\x12\x11\n" +
	"\rCOMPARE_OP_GT\x10\x03\x12\x12\n" +
	"\x0eCOMPARE_OP_GTE\x10\x04\x12\x11\n" +
	"\rCOMPARE_OP_LT\x10\x05\x12\x12\n" +
	"\x0eCOMPARE_OP_LTE\x10\x06*U\n" +
	"\n" +
	"JoinPolicy\x12\x1b\n" +
	"\x17JOIN_POLICY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JOIN_ALL_SUCCESS\x10\x01\x12\x14\n" +
	"\x10JOIN_ANY_SUCCESS\x10\x02B2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_graph_proto_goTypes = []any{
	(NodeKind)(0),          // 0: dag.v1.NodeKind
	(CompareOp)(0),         // 1: dag.v1.CompareOp
	(JoinPolicy)(0),        // 2: dag.v1.JoinPolicy
	(*FieldPredicate)(nil), // 3: dag.v1.FieldPredicate
	(*Condition)(nil),      // 4: dag.v1.Condition
	(*Transition)(nil),     // 5: dag.v1.Transition
	(*WaitNodeConfig)(nil), // 6: dag.v1.WaitNodeConfig
	(*JoinBarrier)(nil),    // 7: dag.v1.JoinBarrier
	(*JoinSpec)(nil),       // 8: dag.v1.JoinSpec
	(*NodeDef)(nil),        // 9: dag.v1.NodeDef
	(*GraphSpec)(nil),      // 10: dag.v1.GraphSpec
	nil,                    // 11: dag.v1.GraphSpec.NodesEntry
	(TerminalOutcome)(0),   // 12: dag.v1.TerminalOutcome
	(*GraphVersion)(nil),   // 13: dag.v1.GraphVersion
}
var file_graph_proto_depIdxs = []int32{
	1,  // 0: dag.v1.FieldPredicate.op:type_name -> dag.v1.CompareOp
	3,  // 1: dag.v1.Condition.field_predicate:type_name -> dag.v1.FieldPredicate
	4,  // 2: dag.v1.Transition.condition:type_name -> dag.v1.Condition
	7,  // 3: dag.v1.JoinSpec.barriers:type_name -> dag.v1.JoinBarrier
	2,  // 4: dag.v1.JoinSpec.policy:type_name -> dag.v1.JoinPolicy
	0,  // 5: dag.v1.NodeDef.kind:type_name -> dag.v1.NodeKind
	5,  // 6: dag.v1.NodeDef.transitions:type_name -> dag.v1.Transition
	12, // 7: dag.v1.NodeDef.terminal_outcome:type_name -> dag.v1.TerminalOutcome
	6,  // 8: dag.v1.NodeDef.wait_config:type_name -> dag.v1.WaitNodeConfig
	8,  // 9: dag.v1.NodeDef.join_spec:type_name -> dag.v1.JoinSpec
	13, // 10: dag.v1.GraphSpec.version:type_name -> dag.v1.GraphVersion
	11, // 11: dag.v1.GraphSpec.nodes:type_name -> dag.v1.GraphSpec.NodesEntry
	9,  // 12: dag.v1.GraphSpec.NodesEntry.value:type_name -> dag.v1.NodeDef
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_common_proto_init()
	file_graph_proto_msgTypes[1].OneofWrappers = []any{
		(*Condition_Always)(nil),
		(*Condition_FieldPredicate)(nil),
	}
	file_graph_proto_msgTypes[4].OneofWrappers = []any{
		(*JoinBarrier_ChildEntityId)(nil),
		(*JoinBarrier_CorrelationId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		EnumInfos:         file_graph_proto_enumTypes,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
