// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionStatus 执行记录状态。
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_PENDING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_COMMITTED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_PENDING",
		2: "EXECUTION_STATUS_RUNNING",
		3: "EXECUTION_STATUS_COMMITTED",
		4: "EXECUTION_STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_PENDING":     1,
		"EXECUTION_STATUS_RUNNING":     2,
		"EXECUTION_STATUS_COMMITTED":   3,
		"EXECUTION_STATUS_FAILED":      4,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

// JournalKind Journal 条目类型。
type JournalKind int32

const (
	JournalKind_JOURNAL_KIND_UNSPECIFIED            JournalKind = 0
	JournalKind_JOURNAL_KIND_NODE_COMMITTED         JournalKind = 1
	JournalKind_JOURNAL_KIND_SIGNAL_RECEIVED        JournalKind = 2
	JournalKind_JOURNAL_KIND_SPAWNED                JournalKind = 3
	JournalKind_JOURNAL_KIND_JOIN_COMMITTED         JournalKind = 4
	JournalKind_JOURNAL_KIND_COMPENSATION_COMMITTED JournalKind = 5
)

// Enum value maps for JournalKind.
var (
	JournalKind_name = map[int32]string{
		0: "JOURNAL_KIND_UNSPECIFIED",
		1: "JOURNAL_KIND_NODE_COMMITTED",
		2: "JOURNAL_KIND_SIGNAL_RECEIVED",
		3: "JOURNAL_KIND_SPAWNED",
		4: "JOURNAL_KIND_JOIN_COMMITTED",
		5: "JOURNAL_KIND_COMPENSATION_COMMITTED",
	}
	JournalKind_value = map[string]int32{
		"JOURNAL_KIND_UNSPECIFIED":            0,
		"JOURNAL_KIND_NODE_COMMITTED":         1,
		"JOURNAL_KIND_SIGNAL_RECEIVED":        2,
		"JOURNAL_KIND_SPAWNED":                3,
		"JOURNAL_KIND_JOIN_COMMITTED":         4,
		"JOURNAL_KIND_COMPENSATION_COMMITTED": 5,
	}
)

func (x JournalKind) Enum() *JournalKind {
	p := new(JournalKind)
	*p = x
	return p
}

func (x JournalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JournalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[1].Descriptor()
}

func (JournalKind) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[1]
}

func (x JournalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JournalKind.Descriptor instead.
func (JournalKind) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

// StartInstanceRequest 启动实例请求。
type StartInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            *EntityRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	TypeKey        *EntityTypeKey         `protobuf:"bytes,2,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	InitialPayload *anypb.Any             `protobuf:"bytes,3,opt,name=initial_payload,json=initialPayload,proto3" json:"initial_payload,omitempty"`
	GraphVersion   *GraphVersion          `protobuf:"bytes,4,opt,name=graph_version,json=graphVersion,proto3" json:"graph_version,omitempty"`
	GraphPinPolicy GraphPinPolicy         `protobuf:"varint,5,opt,name=graph_pin_policy,json=graphPinPolicy,proto3,enum=dag.v1.GraphPinPolicy" json:"graph_pin_policy,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Parent         *EntityRef             `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *StartInstanceRequest) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *StartInstanceRequest) GetTypeKey() *EntityTypeKey {
	if x != nil {
		return x.TypeKey
	}
	return nil
}

func (x *StartInstanceRequest) GetInitialPayload() *anypb.Any {
	if x != nil {
		return x.InitialPayload
	}
	return nil
}

func (x *StartInstanceRequest) GetGraphVersion() *GraphVersion {
	if x != nil {
		return x.GraphVersion
	}
	return nil
}

func (x *StartInstanceRequest) GetGraphPinPolicy() GraphPinPolicy {
	if x != nil {
		return x.GraphPinPolicy
	}
	return GraphPinPolicy_GRAPH_PIN_POLICY_UNSPECIFIED
}

func (x *StartInstanceRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *StartInstanceRequest) GetParent() *EntityRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

// ExecutionRecord hop 执行记录。
type ExecutionRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	EntityId       string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InputSequence  int64                  `protobuf:"varint,4,opt,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	Status         ExecutionStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=dag.v1.ExecutionStatus" json:"status,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CommittedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionRecord) Reset() {
	*x = ExecutionRecord{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRecord) ProtoMessage() {}

func (x *ExecutionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRecord.ProtoReflect.Descriptor instead.
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionRecord) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecutionRecord) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ExecutionRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionRecord) GetInputSequence() int64 {
	if x != nil {
		return x.InputSequence
	}
	return 0
}

func (x *ExecutionRecord) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ExecutionRecord) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ExecutionRecord) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionRecord) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

// SignalDelivery 信号投递。
type SignalDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalDelivery) Reset() {
	*x = SignalDelivery{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalDelivery) ProtoMessage() {}

func (x *SignalDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalDelivery.ProtoReflect.Descriptor instead.
func (*SignalDelivery) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *SignalDelivery) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SignalDelivery) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *SignalDelivery) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// LineJournalEntry 线 Journal 条目。
type LineJournalEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JournalSequence   int64                  `protobuf:"varint,1,opt,name=journal_sequence,json=journalSequence,proto3" json:"journal_sequence,omitempty"`
	Kind              JournalKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=dag.v1.JournalKind" json:"kind,omitempty"`
	NodeId            string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InputSequence     int64                  `protobuf:"varint,4,opt,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	OutputSequence    int64                  `protobuf:"varint,5,opt,name=output_sequence,json=outputSequence,proto3" json:"output_sequence,omitempty"`
	OutputSnapshot    *EntitySnapshot        `protobuf:"bytes,6,opt,name=output_snapshot,json=outputSnapshot,proto3" json:"output_snapshot,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CommittedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	SignalName        string                 `protobuf:"bytes,9,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	DeliveryId        string                 `protobuf:"bytes,10,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	SpawnedRef        *EntityRef             `protobuf:"bytes,11,opt,name=spawned_ref,json=spawnedRef,proto3" json:"spawned_ref,omitempty"`
	CompensationFrame *CompensationFrame     `protobuf:"bytes,12,opt,name=compensation_frame,json=compensationFrame,proto3" json:"compensation_frame,omitempty"`
	SpawnedRefs       []*EntityRef           `protobuf:"bytes,13,rep,name=spawned_refs,json=spawnedRefs,proto3" json:"spawned_refs,omitempty"`
	FailureReason     string                 `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LineJournalEntry) Reset() {
	*x = LineJournalEntry{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineJournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineJournalEntry) ProtoMessage() {}

func (x *LineJournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineJournalEntry.ProtoReflect.Descriptor instead.
func (*LineJournalEntry) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *LineJournalEntry) GetJournalSequence() int64 {
	if x != nil {
		return x.JournalSequence
	}
	return 0
}

func (x *LineJournalEntry) GetKind() JournalKind {
	if x != nil {
		return x.Kind
	}
	return JournalKind_JOURNAL_KIND_UNSPECIFIED
}

func (x *LineJournalEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LineJournalEntry) GetInputSequence() int64 {
	if x != nil {
		return x.InputSequence
	}
	return 0
}

func (x *LineJournalEntry) GetOutputSequence() int64 {
	if x != nil {
		return x.OutputSequence
	}
	return 0
}

func (x *LineJournalEntry) GetOutputSnapshot() *EntitySnapshot {
	if x != nil {
		return x.OutputSnapshot
	}
	return nil
}

func (x *LineJournalEntry) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LineJournalEntry) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *LineJournalEntry) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *LineJournalEntry) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *LineJournalEntry) GetSpawnedRef() *EntityRef {
	if x != nil {
		return x.SpawnedRef
	}
	return nil
}

func (x *LineJournalEntry) GetCompensationFrame() *CompensationFrame {
	if x != nil {
		return x.CompensationFrame
	}
	return nil
}

func (x *LineJournalEntry) GetSpawnedRefs() []*EntityRef {
	if x != nil {
		return x.SpawnedRefs
	}
	return nil
}

func (x *LineJournalEntry) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

// HopCommit hop 提交载荷。
type HopCommit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            *EntityRef             `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InputSequence  int64                  `protobuf:"varint,3,opt,name=input_sequence,json=inputSequence,proto3" json:"input_sequence,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OutputSnapshot *EntitySnapshot        `protobuf:"bytes,5,opt,name=output_snapshot,json=outputSnapshot,proto3" json:"output_snapshot,omitempty"`
	NextNodeId     string                 `protobuf:"bytes,6,opt,name=next_node_id,json=nextNodeId,proto3" json:"next_node_id,omitempty"`
	NextStatus     InstanceStatus         `protobuf:"varint,7,opt,name=next_status,json=nextStatus,proto3,enum=dag.v1.InstanceStatus" json:"next_status,omitempty"`
	SagaDelta      *SagaState             `protobuf:"bytes,8,opt,name=saga_delta,json=sagaDelta,proto3" json:"saga_delta,omitempty"`
	Spawned        []*EntityRef           `protobuf:"bytes,9,rep,name=spawned,proto3" json:"spawned,omitempty"`
	JournalKind    JournalKind            `protobuf:"varint,10,opt,name=journal_kind,json=journalKind,proto3,enum=dag.v1.JournalKind" json:"journal_kind,omitempty"`
	SignalName     string                 `protobuf:"bytes,11,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	DeliveryId     string                 `protobuf:"bytes,12,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	FailureReason  string                 `protobuf:"bytes,13,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HopCommit) Reset() {
	*x = HopCommit{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HopCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HopCommit) ProtoMessage() {}

func (x *HopCommit) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HopCommit.ProtoReflect.Descriptor instead.
func (*HopCommit) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *HopCommit) GetRef() *EntityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *HopCommit) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HopCommit) GetInputSequence() int64 {
	if x != nil {
		return x.InputSequence
	}
	return 0
}

func (x *HopCommit) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *HopCommit) GetOutputSnapshot() *EntitySnapshot {
	if x != nil {
		return x.OutputSnapshot
	}
	return nil
}

func (x *HopCommit) GetNextNodeId() string {
	if x != nil {
		return x.NextNodeId
	}
	return ""
}

func (x *HopCommit) GetNextStatus() InstanceStatus {
	if x != nil {
		return x.NextStatus
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *HopCommit) GetSagaDelta() *SagaState {
	if x != nil {
		return x.SagaDelta
	}
	return nil
}

func (x *HopCommit) GetSpawned() []*EntityRef {
	if x != nil {
		return x.Spawned
	}
	return nil
}

func (x *HopCommit) GetJournalKind() JournalKind {
	if x != nil {
		return x.JournalKind
	}
	return JournalKind_JOURNAL_KIND_UNSPECIFIED
}

func (x *HopCommit) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *HopCommit) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *HopCommit) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\x06dag.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\fentity.proto\x1a\n" +
	"saga.proto\"\xfb\x02\n" +
	"\x14StartInstanceRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.dag.v1.EntityRefR\x03ref\x120\n" +
	"\btype_key\x18\x02 \x01(\v2\x15.dag.v1.EntityTypeKeyR\atypeKey\x12=\n" +
	"\x0finitial_payload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x0einitialPayload\x129\n" +
	"\rgraph_version\x18\x04 \x01(\v2\x14.dag.v1.GraphVersionR\fgraphVersion\x12@\n" +
	"\x10graph_pin_policy\x18\x05 \x01(\x0e2\x16.dag.v1.GraphPinPolicyR\x0egraphPinPolicy\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12)\n" +
	"\x06parent\x18\a \x01(\v2\x11.dag.v1.EntityRefR\x06parent\"\xdc\x02\n" +
	"\x0fExecutionRecord\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einput_sequence\x18\x04 \x01(\x03R\rinputSequence\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.dag.v1.ExecutionStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcommitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\"\x9f\x01\n" +
	"\x0eSignalDelivery\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x12\x1f\n" +
	"\vdelivery_id\x18\x03 \x01(\tR\n" +
	"deliveryId\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x95\x05\n" +
	"\x10LineJournalEntry\x12)\n" +
	"\x10journal_sequence\x18\x01 \x01(\x03R\x0fjournalSequence\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.dag.v1.JournalKindR\x04kind\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einput_sequence\x18\x04 \x01(\x03R\rinputSequence\x12'\n" +
	"\x0foutput_sequence\x18\x05 \x01(\x03R\x0eoutputSequence\x12?\n" +
	"\x0foutput_snapshot\x18\x06 \x01(\v2\x16.dag.v1.EntitySnapshotR\x0eoutputSnapshot\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\fcommitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x12\x1f\n" +
	"\vsignal_name\x18\t \x01(\tR\n" +
	"signalName\x12\x1f\n" +
	"\vdelivery_id\x18\n" +
	" \x01(\tR\n" +
	"deliveryId\x122\n" +
	"\vspawned_ref\x18\v \x01(\v2\x11.dag.v1.EntityRefR\n" +
	"spawnedRef\x12H\n" +
	"\x12compensation_frame\x18\f \x01(\v2\x19.dag.v1.CompensationFrameR\x11compensationFrame\x124\n" +
	"\fspawned_refs\x18\r \x03(\v2\x11.dag.v1.EntityRefR\vspawnedRefs\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\"\xb5\x04\n" +
	"\tHopCommit\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.dag.v1.EntityRefR\x03ref\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einput_sequence\x18\x03 \x01(\x03R\rinputSequence\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12?\n" +
	"\x0foutput_snapshot\x18\x05 \x01(\v2\x16.dag.v1.EntitySnapshotR\x0eoutputSnapshot\x12 \n" +
	"\fnext_node_id\x18\x06 \x01(\tR\n" +
	"nextNodeId\x127\n" +
	"\vnext_status\x18\a \x01(\x0e2\x16.dag.v1.InstanceStatusR\n" +
	"nextStatus\x120\n" +
	"\n" +
	"saga_delta\x18\b \x01(\v2\x11.dag.v1.SagaStateR\tsagaDelta\x12+\n" +
	"\aspawned\x18\t \x03(\v2\x11.dag.v1.EntityRefR\aspawned\x126\n" +
	"\fjournal_kind\x18\n" +
	" \x01(\x0e2\x13.dag.v1.JournalKindR\vjournalKind\x12\x1f\n" +
	"\vsignal_name\x18\v \x01(\tR\n" +
	"signalName\x12\x1f\n" +
	"\vdelivery_id\x18\f \x01(\tR\n" +
	"deliveryId\x12%\n" +
	"\x0efailure_reason\x18\r \x01(\tR\rfailureReason*\xac\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_COMMITTED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x04*\xd2\x01\n" +
	"\vJournalKind\x12\x1c\n" +
	"\x18JOURNAL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bJOURNAL_KIND_NODE_COMMITTED\x10\x01\x12 \n" +
	"\x1cJOURNAL_KIND_SIGNAL_RECEIVED\x10\x02\x12\x18\n" +
	"\x14JOURNAL_KIND_SPAWNED\x10\x03\x12\x1f\n" +
	"\x1bJOURNAL_KIND_JOIN_COMMITTED\x10\x04\x12'\n" +
	"#JOURNAL_KIND_COMPENSATION_COMMITTED\x10\x05B2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_runtime_proto_goTypes = []any{
	(ExecutionStatus)(0),          // 0: dag.v1.ExecutionStatus
	(JournalKind)(0),              // 1: dag.v1.JournalKind
	(*StartInstanceRequest)(nil),  // 2: dag.v1.StartInstanceRequest
	(*ExecutionRecord)(nil),       // 3: dag.v1.ExecutionRecord
	(*SignalDelivery)(nil),        // 4: dag.v1.SignalDelivery
	(*LineJournalEntry)(nil),      // 5: dag.v1.LineJournalEntry
	(*HopCommit)(nil),             // 6: dag.v1.HopCommit
	(*EntityRef)(nil),             // 7: dag.v1.EntityRef
	(*EntityTypeKey)(nil),         // 8: dag.v1.EntityTypeKey
	(*anypb.Any)(nil),             // 9: google.protobuf.Any
	(*GraphVersion)(nil),          // 10: dag.v1.GraphVersion
	(GraphPinPolicy)(0),           // 11: dag.v1.GraphPinPolicy
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*EntitySnapshot)(nil),        // 13: dag.v1.EntitySnapshot
	(*CompensationFrame)(nil),     // 14: dag.v1.CompensationFrame
	(InstanceStatus)(0),           // 15: dag.v1.InstanceStatus
	(*SagaState)(nil),             // 16: dag.v1.SagaState
}
var file_runtime_proto_depIdxs = []int32{
	7,  // 0: dag.v1.StartInstanceRequest.ref:type_name -> dag.v1.EntityRef
	8,  // 1: dag.v1.StartInstanceRequest.type_key:type_name -> dag.v1.EntityTypeKey
	9,  // 2: dag.v1.StartInstanceRequest.initial_payload:type_name -> google.protobuf.Any
	10, // 3: dag.v1.StartInstanceRequest.graph_version:type_name -> dag.v1.GraphVersion
	11, // 4: dag.v1.StartInstanceRequest.graph_pin_policy:type_name -> dag.v1.GraphPinPolicy
	7,  // 5: dag.v1.StartInstanceRequest.parent:type_name -> dag.v1.EntityRef
	0,  // 6: dag.v1.ExecutionRecord.status:type_name -> dag.v1.ExecutionStatus
	12, // 7: dag.v1.ExecutionRecord.started_at:type_name -> google.protobuf.Timestamp
	12, // 8: dag.v1.ExecutionRecord.committed_at:type_name -> google.protobuf.Timestamp
	9,  // 9: dag.v1.SignalDelivery.payload:type_name -> google.protobuf.Any
	1,  // 10: dag.v1.LineJournalEntry.kind:type_name -> dag.v1.JournalKind
	13, // 11: dag.v1.LineJournalEntry.output_snapshot:type_name -> dag.v1.EntitySnapshot
	12, // 12: dag.v1.LineJournalEntry.committed_at:type_name -> google.protobuf.Timestamp
	7,  // 13: dag.v1.LineJournalEntry.spawned_ref:type_name -> dag.v1.EntityRef
	14, // 14: dag.v1.LineJournalEntry.compensation_frame:type_name -> dag.v1.CompensationFrame
	7,  // 15: dag.v1.LineJournalEntry.spawned_refs:type_name -> dag.v1.EntityRef
	7,  // 16: dag.v1.HopCommit.ref:type_name -> dag.v1.EntityRef
	13, // 17: dag.v1.HopCommit.output_snapshot:type_name -> dag.v1.EntitySnapshot
	15, // 18: dag.v1.HopCommit.next_status:type_name -> dag.v1.InstanceStatus
	16, // 19: dag.v1.HopCommit.saga_delta:type_name -> dag.v1.SagaState
	7,  // 20: dag.v1.HopCommit.spawned:type_name -> dag.v1.EntityRef
	1,  // 21: dag.v1.HopCommit.journal_kind:type_name -> dag.v1.JournalKind
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	file_common_proto_init()
	file_entity_proto_init()
	file_saga_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		EnumInfos:         file_runtime_proto_enumTypes,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
