// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: saga.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompensationFrame 补偿栈帧。
type CompensationFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UnitId            string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	CompensatorUnitId string                 `protobuf:"bytes,3,opt,name=compensator_unit_id,json=compensatorUnitId,proto3" json:"compensator_unit_id,omitempty"`
	ForwardSequence   int64                  `protobuf:"varint,4,opt,name=forward_sequence,json=forwardSequence,proto3" json:"forward_sequence,omitempty"`
	ForwardSnapshot   *anypb.Any             `protobuf:"bytes,5,opt,name=forward_snapshot,json=forwardSnapshot,proto3" json:"forward_snapshot,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompensationFrame) Reset() {
	*x = CompensationFrame{}
	mi := &file_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationFrame) ProtoMessage() {}

func (x *CompensationFrame) ProtoReflect() protoreflect.Message {
	mi := &file_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationFrame.ProtoReflect.Descriptor instead.
func (*CompensationFrame) Descriptor() ([]byte, []int) {
	return file_saga_proto_rawDescGZIP(), []int{0}
}

func (x *CompensationFrame) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CompensationFrame) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *CompensationFrame) GetCompensatorUnitId() string {
	if x != nil {
		return x.CompensatorUnitId
	}
	return ""
}

func (x *CompensationFrame) GetForwardSequence() int64 {
	if x != nil {
		return x.ForwardSequence
	}
	return 0
}

func (x *CompensationFrame) GetForwardSnapshot() *anypb.Any {
	if x != nil {
		return x.ForwardSnapshot
	}
	return nil
}

// CompensationRecord 补偿执行记录。
type CompensationRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey    string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CompensatorUnitId string                 `protobuf:"bytes,2,opt,name=compensator_unit_id,json=compensatorUnitId,proto3" json:"compensator_unit_id,omitempty"`
	ForwardSequence   int64                  `protobuf:"varint,3,opt,name=forward_sequence,json=forwardSequence,proto3" json:"forward_sequence,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompensationRecord) Reset() {
	*x = CompensationRecord{}
	mi := &file_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationRecord) ProtoMessage() {}

func (x *CompensationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationRecord.ProtoReflect.Descriptor instead.
func (*CompensationRecord) Descriptor() ([]byte, []int) {
	return file_saga_proto_rawDescGZIP(), []int{1}
}

func (x *CompensationRecord) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CompensationRecord) GetCompensatorUnitId() string {
	if x != nil {
		return x.CompensatorUnitId
	}
	return ""
}

func (x *CompensationRecord) GetForwardSequence() int64 {
	if x != nil {
		return x.ForwardSequence
	}
	return 0
}

func (x *CompensationRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CompensationContext 补偿上下文。
type CompensationContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityId        string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ForwardSequence int64                  `protobuf:"varint,3,opt,name=forward_sequence,json=forwardSequence,proto3" json:"forward_sequence,omitempty"`
	Snapshot        *anypb.Any             `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompensationContext) Reset() {
	*x = CompensationContext{}
	mi := &file_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationContext) ProtoMessage() {}

func (x *CompensationContext) ProtoReflect() protoreflect.Message {
	mi := &file_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationContext.ProtoReflect.Descriptor instead.
func (*CompensationContext) Descriptor() ([]byte, []int) {
	return file_saga_proto_rawDescGZIP(), []int{2}
}

func (x *CompensationContext) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CompensationContext) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CompensationContext) GetForwardSequence() int64 {
	if x != nil {
		return x.ForwardSequence
	}
	return 0
}

func (x *CompensationContext) GetSnapshot() *anypb.Any {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// SagaState Saga 持久化状态。
type SagaState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stack         []*CompensationFrame   `protobuf:"bytes,1,rep,name=stack,proto3" json:"stack,omitempty"`
	Records       []*CompensationRecord  `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaState) Reset() {
	*x = SagaState{}
	mi := &file_saga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaState) ProtoMessage() {}

func (x *SagaState) ProtoReflect() protoreflect.Message {
	mi := &file_saga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaState.ProtoReflect.Descriptor instead.
func (*SagaState) Descriptor() ([]byte, []int) {
	return file_saga_proto_rawDescGZIP(), []int{3}
}

func (x *SagaState) GetStack() []*CompensationFrame {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *SagaState) GetRecords() []*CompensationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_saga_proto protoreflect.FileDescriptor

const file_saga_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"saga.proto\x12\x06dag.v1\x1a\x19google/protobuf/any.proto\"\xe1\x01\n" +
	"\x11CompensationFrame\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\x12.\n" +
	"\x13compensator_unit_id\x18\x03 \x01(\tR\x11compensatorUnitId\x12)\n" +
	"\x10forward_sequence\x18\x04 \x01(\x03R\x0fforwardSequence\x12?\n" +
	"\x10forward_snapshot\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x0fforwardSnapshot\"\xb0\x01\n" +
	"\x12CompensationRecord\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x13compensator_unit_id\x18\x02 \x01(\tR\x11compensatorUnitId\x12)\n" +
	"\x10forward_sequence\x18\x03 \x01(\x03R\x0fforwardSequence\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xa8\x01\n" +
	"\x13CompensationContext\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12)\n" +
	"\x10forward_sequence\x18\x03 \x01(\x03R\x0fforwardSequence\x120\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\bsnapshot\"r\n" +
	"\tSagaState\x12/\n" +
	"\x05stack\x18\x01 \x03(\v2\x19.dag.v1.CompensationFrameR\x05stack\x124\n" +
	"\arecords\x18\x02 \x03(\v2\x1a.dag.v1.CompensationRecordR\arecordsB2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_saga_proto_rawDescOnce sync.Once
	file_saga_proto_rawDescData []byte
)

func file_saga_proto_rawDescGZIP() []byte {
	file_saga_proto_rawDescOnce.Do(func() {
		file_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saga_proto_rawDesc), len(file_saga_proto_rawDesc)))
	})
	return file_saga_proto_rawDescData
}

var file_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_saga_proto_goTypes = []any{
	(*CompensationFrame)(nil),   // 0: dag.v1.CompensationFrame
	(*CompensationRecord)(nil),  // 1: dag.v1.CompensationRecord
	(*CompensationContext)(nil), // 2: dag.v1.CompensationContext
	(*SagaState)(nil),           // 3: dag.v1.SagaState
	(*anypb.Any)(nil),           // 4: google.protobuf.Any
}
var file_saga_proto_depIdxs = []int32{
	4, // 0: dag.v1.CompensationFrame.forward_snapshot:type_name -> google.protobuf.Any
	4, // 1: dag.v1.CompensationContext.snapshot:type_name -> google.protobuf.Any
	0, // 2: dag.v1.SagaState.stack:type_name -> dag.v1.CompensationFrame
	1, // 3: dag.v1.SagaState.records:type_name -> dag.v1.CompensationRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_saga_proto_init() }
func file_saga_proto_init() {
	if File_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saga_proto_rawDesc), len(file_saga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saga_proto_goTypes,
		DependencyIndexes: file_saga_proto_depIdxs,
		MessageInfos:      file_saga_proto_msgTypes,
	}.Build()
	File_saga_proto = out.File
	file_saga_proto_goTypes = nil
	file_saga_proto_depIdxs = nil
}
