// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: unit.proto

package dagv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SideEffectClass 副作用分类。
type SideEffectClass int32

const (
	SideEffectClass_SIDE_EFFECT_UNSPECIFIED SideEffectClass = 0
	SideEffectClass_SIDE_EFFECT_NONE        SideEffectClass = 1
	SideEffectClass_SIDE_EFFECT_IDEMPOTENT  SideEffectClass = 2
	SideEffectClass_SIDE_EFFECT_EXTERNAL    SideEffectClass = 3
)

// Enum value maps for SideEffectClass.
var (
	SideEffectClass_name = map[int32]string{
		0: "SIDE_EFFECT_UNSPECIFIED",
		1: "SIDE_EFFECT_NONE",
		2: "SIDE_EFFECT_IDEMPOTENT",
		3: "SIDE_EFFECT_EXTERNAL",
	}
	SideEffectClass_value = map[string]int32{
		"SIDE_EFFECT_UNSPECIFIED": 0,
		"SIDE_EFFECT_NONE":        1,
		"SIDE_EFFECT_IDEMPOTENT":  2,
		"SIDE_EFFECT_EXTERNAL":    3,
	}
)

func (x SideEffectClass) Enum() *SideEffectClass {
	p := new(SideEffectClass)
	*p = x
	return p
}

func (x SideEffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SideEffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_unit_proto_enumTypes[0].Descriptor()
}

func (SideEffectClass) Type() protoreflect.EnumType {
	return &file_unit_proto_enumTypes[0]
}

func (x SideEffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SideEffectClass.Descriptor instead.
func (SideEffectClass) EnumDescriptor() ([]byte, []int) {
	return file_unit_proto_rawDescGZIP(), []int{0}
}

// ComputeUnitDef 计算单元定义。
type ComputeUnitDef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UnitId          string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	InputTypeKey    *EntityTypeKey         `protobuf:"bytes,2,opt,name=input_type_key,json=inputTypeKey,proto3" json:"input_type_key,omitempty"`
	OutputTypeKeys  []*EntityTypeKey       `protobuf:"bytes,3,rep,name=output_type_keys,json=outputTypeKeys,proto3" json:"output_type_keys,omitempty"`
	SideEffectClass SideEffectClass        `protobuf:"varint,4,opt,name=side_effect_class,json=sideEffectClass,proto3,enum=dag.v1.SideEffectClass" json:"side_effect_class,omitempty"`
	RetryPolicy     *RetryPolicy           `protobuf:"bytes,5,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeUnitDef) Reset() {
	*x = ComputeUnitDef{}
	mi := &file_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeUnitDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeUnitDef) ProtoMessage() {}

func (x *ComputeUnitDef) ProtoReflect() protoreflect.Message {
	mi := &file_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeUnitDef.ProtoReflect.Descriptor instead.
func (*ComputeUnitDef) Descriptor() ([]byte, []int) {
	return file_unit_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeUnitDef) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ComputeUnitDef) GetInputTypeKey() *EntityTypeKey {
	if x != nil {
		return x.InputTypeKey
	}
	return nil
}

func (x *ComputeUnitDef) GetOutputTypeKeys() []*EntityTypeKey {
	if x != nil {
		return x.OutputTypeKeys
	}
	return nil
}

func (x *ComputeUnitDef) GetSideEffectClass() SideEffectClass {
	if x != nil {
		return x.SideEffectClass
	}
	return SideEffectClass_SIDE_EFFECT_UNSPECIFIED
}

func (x *ComputeUnitDef) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

var File_unit_proto protoreflect.FileDescriptor

const file_unit_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"unit.proto\x12\x06dag.v1\x1a\fcommon.proto\"\xa4\x02\n" +
	"\x0eComputeUnitDef\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12;\n" +
	"\x0einput_type_key\x18\x02 \x01(\v2\x15.dag.v1.EntityTypeKeyR\finputTypeKey\x12?\n" +
	"\x10output_type_keys\x18\x03 \x03(\v2\x15.dag.v1.EntityTypeKeyR\x0eoutputTypeKeys\x12C\n" +
	"\x11side_effect_class\x18\x04 \x01(\x0e2\x17.dag.v1.SideEffectClassR\x0fsideEffectClass\x126\n" +
	"\fretry_policy\x18\x05 \x01(\v2\x13.dag.v1.RetryPolicyR\vretryPolicy*z\n" +
	"\x0fSideEffectClass\x12\x1b\n" +
	"\x17SIDE_EFFECT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SIDE_EFFECT_NONE\x10\x01\x12\x1a\n" +
	"\x16SIDE_EFFECT_IDEMPOTENT\x10\x02\x12\x18\n" +
	"\x14SIDE_EFFECT_EXTERNAL\x10\x03B2Z0github.com/solo-kingdom/uniface/api/dag/v1;dagv1b\x06proto3"

var (
	file_unit_proto_rawDescOnce sync.Once
	file_unit_proto_rawDescData []byte
)

func file_unit_proto_rawDescGZIP() []byte {
	file_unit_proto_rawDescOnce.Do(func() {
		file_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unit_proto_rawDesc), len(file_unit_proto_rawDesc)))
	})
	return file_unit_proto_rawDescData
}

var file_unit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_unit_proto_goTypes = []any{
	(SideEffectClass)(0),   // 0: dag.v1.SideEffectClass
	(*ComputeUnitDef)(nil), // 1: dag.v1.ComputeUnitDef
	(*EntityTypeKey)(nil),  // 2: dag.v1.EntityTypeKey
	(*RetryPolicy)(nil),    // 3: dag.v1.RetryPolicy
}
var file_unit_proto_depIdxs = []int32{
	2, // 0: dag.v1.ComputeUnitDef.input_type_key:type_name -> dag.v1.EntityTypeKey
	2, // 1: dag.v1.ComputeUnitDef.output_type_keys:type_name -> dag.v1.EntityTypeKey
	0, // 2: dag.v1.ComputeUnitDef.side_effect_class:type_name -> dag.v1.SideEffectClass
	3, // 3: dag.v1.ComputeUnitDef.retry_policy:type_name -> dag.v1.RetryPolicy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_unit_proto_init() }
func file_unit_proto_init() {
	if File_unit_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unit_proto_rawDesc), len(file_unit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unit_proto_goTypes,
		DependencyIndexes: file_unit_proto_depIdxs,
		EnumInfos:         file_unit_proto_enumTypes,
		MessageInfos:      file_unit_proto_msgTypes,
	}.Build()
	File_unit_proto = out.File
	file_unit_proto_goTypes = nil
	file_unit_proto_depIdxs = nil
}
