services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    profiles: ["kv", "all"]

  consul:
    image: hashicorp/consul:1.19
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    profiles: ["config", "all"]

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
    profiles: ["queue", "all"]

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    profiles: ["queue-kafka", "all"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles: ["queue-rabbit", "all"]

  aerospike:
    image: aerospike/aerospike-server:7.1.0.0
    ports:
      - "3001:3000"
    profiles: ["kv-aerospike", "all"]
